# Generated by Django 6.0.3 on 2026-03-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id_norma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'normas',
                'unique_together': {('codigo', 'ano', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('engenheiro', models.ForeignKey(db_column='engenheiro_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('hash_arquivo', models.CharField(max_length=255, unique=True)),
                ('caminho_arquivo', models.TextField()),
                ('tipo_arquivo', models.CharField(max_length=50)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'arquivos',
            },
        ),
        migrations.CreateModel(
            name='ProjetoNorma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('norma', models.ForeignKey(db_column='norma_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.norma')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'projeto_norma',
            },
        ),
    ]
