# Generated by Django 6.0.3 on 2026-03-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='caminho_arquivo',
            field=models.FileField(upload_to='cad_arquivos/'),
        ),
    ]
