# Generated by Django 5.2.12 on 2026-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Em revisão', 'Em revisão'), ('Concluído', 'Concluído')], default='Pendente', max_length=50),
        ),
    ]
