# Generated by Django 6.0.3 on 2026-04-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Em revisão', 'Em revisão'), ('Concluído', 'Concluído')], default='Pendente', max_length=50),
        ),
        migrations.CreateModel(
            name='EspecificacaoIA',
            fields=[
                ('id_especificacao', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='especificacoes/')),
                ('titulo', models.CharField(max_length=255)),
                ('versao', models.CharField(default='1.0', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, related_name='especificacoes', to='projetos.projeto')),
            ],
            options={
                'db_table': 'especificacoes_ia',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
