# Generated by Django 6.0.3 on 2026-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_especificacao_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
