# Generated by Django 6.0.3 on 2026-04-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_status'),
        ('projetos', '0004_add_atualizado_em_projeto'),
    ]

    operations = [
    ]
