# Generated by Django 6.0.3 on 2026-04-27 22:46

import apps.projetos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_merge_20260420_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='caminho_arquivo',
            field=models.FileField(upload_to=apps.projetos.models.UploadDeArquivo),
        ),
    ]
