# Generated by Django 6.0.3 on 2026-04-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_arquivo_caminho_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='normas',
        ),
        migrations.AlterField(
            model_name='projetonorma',
            name='norma',
            field=models.CharField(max_length=255),
        ),
    ]
