# Generated by Django 6.0.3 on 2026-04-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_remove_projeto_normas_alter_projetonorma_norma'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
