# Generated by Django 6.0.3 on 2026-03-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ambiente', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'ambientes',
            },
        ),
        migrations.CreateModel(
            name='CircuitoEletrico',
            fields=[
                ('id_circuito', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('disjuntor', models.IntegerField(null=True)),
                ('secao_cabo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'circuitos_eletricos',
            },
        ),
        migrations.CreateModel(
            name='Demolicao',
            fields=[
                ('id_demolicao', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=100)),
                ('descricao', models.TextField(null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'demolicoes',
            },
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id_dimensao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='m', max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'dimensoes',
            },
        ),
        migrations.CreateModel(
            name='Esquadria',
            fields=[
                ('id_esquadria', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
                ('ambiente', models.ForeignKey(db_column='ambiente_id', on_delete=django.db.models.deletion.CASCADE, to='calculos.ambiente')),
            ],
            options={
                'db_table': 'esquadrias',
            },
        ),
        migrations.CreateModel(
            name='EstruturaElemento',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume_concreto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('peso_ferragem', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'estrutura_elementos',
            },
        ),
        migrations.CreateModel(
            name='MovimentoSolo',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unidade', models.CharField(default='m3', max_length=20)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'movimento_solo',
            },
        ),
        migrations.CreateModel(
            name='PontoEletrico',
            fields=[
                ('id_ponto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('potencia', models.IntegerField(null=True)),
                ('altura_instalacao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ambiente', models.ForeignKey(db_column='ambiente_id', on_delete=django.db.models.deletion.CASCADE, to='calculos.ambiente')),
                ('circuito', models.ForeignKey(db_column='circuito_id', on_delete=django.db.models.deletion.CASCADE, to='calculos.circuitoeletrico')),
            ],
            options={
                'db_table': 'pontos_eletricos',
            },
        ),
        migrations.CreateModel(
            name='RamalHidraulico',
            fields=[
                ('id_ramal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ramal', models.CharField(max_length=50)),
                ('diametro', models.IntegerField(null=True)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'ramais_hidraulicos',
            },
        ),
        migrations.CreateModel(
            name='PontoHidraulico',
            fields=[
                ('id_ponto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('diametro', models.IntegerField(null=True)),
                ('ambiente', models.ForeignKey(db_column='ambiente_id', on_delete=django.db.models.deletion.CASCADE, to='calculos.ambiente')),
                ('ramal', models.ForeignKey(db_column='ramal_id', on_delete=django.db.models.deletion.CASCADE, to='calculos.ramalhidraulico')),
            ],
            options={
                'db_table': 'pontos_hidraulicos',
            },
        ),
        migrations.CreateModel(
            name='SPDA',
            fields=[
                ('id_spda', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100, null=True)),
                ('secao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'spda',
            },
        ),
    ]
