# Generated by Django 6.0.3 on 2026-03-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoeletrico',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='pontohidraulico',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='esquadria',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='circuitoeletrico',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='pontoeletrico',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='demolicao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='dimensao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='estruturaelemento',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='movimentosolo',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='pontohidraulico',
            name='ramal',
        ),
        migrations.RemoveField(
            model_name='ramalhidraulico',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='spda',
            name='projeto',
        ),
        migrations.DeleteModel(
            name='Ambiente',
        ),
        migrations.DeleteModel(
            name='Esquadria',
        ),
        migrations.DeleteModel(
            name='CircuitoEletrico',
        ),
        migrations.DeleteModel(
            name='PontoEletrico',
        ),
        migrations.DeleteModel(
            name='Demolicao',
        ),
        migrations.DeleteModel(
            name='Dimensao',
        ),
        migrations.DeleteModel(
            name='EstruturaElemento',
        ),
        migrations.DeleteModel(
            name='MovimentoSolo',
        ),
        migrations.DeleteModel(
            name='PontoHidraulico',
        ),
        migrations.DeleteModel(
            name='RamalHidraulico',
        ),
        migrations.DeleteModel(
            name='SPDA',
        ),
    ]
