# Generated by Django 6.0.3 on 2026-03-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0004_ambiente_projeto'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='projetos.projeto'),
        ),
    ]
