# Generated by Django 6.0.3 on 2026-03-23 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=120)),
                ('email_usuario', models.EmailField(max_length=150, unique=True)),
                ('senha_usuario', models.CharField(max_length=255)),
                ('nivel_usuario', models.CharField(max_length=50)),
                ('status', models.CharField(default='Ativo', max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
