# Generated by Django 6.0.3 on 2026-03-20 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDXF',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'arquivos_dxf',
            },
        ),
        migrations.CreateModel(
            name='DadosExtraidos',
            fields=[
                ('id_dados', models.AutoField(primary_key=True, serialize=False)),
                ('dados_binarios', models.BinaryField(blank=True, null=True)),
                ('arquivo', models.ForeignKey(db_column='arquivo_id', on_delete=django.db.models.deletion.CASCADE, to='dados_ia.arquivodxf')),
            ],
            options={
                'db_table': 'dados_extraidos',
            },
        ),
        migrations.CreateModel(
            name='DadosInseridosManualmente',
            fields=[
                ('id_dados', models.AutoField(primary_key=True, serialize=False)),
                ('dados', models.JSONField()),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'dados_inseridos_manualmente',
            },
        ),
        migrations.CreateModel(
            name='LogValidacao',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('dados', models.JSONField()),
                ('norma', models.ForeignKey(db_column='norma_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.norma')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'logs_validacao',
            },
        ),
    ]
