# Generated by Django 5.2.12 on 2026-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='relatorios/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
