# Generated by Django 6.0.3 on 2026-03-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_ia', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosextraidos',
            name='arquivo',
            field=models.ForeignKey(db_column='arquivo_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.arquivo'),
        ),
        migrations.DeleteModel(
            name='ArquivoDXF',
        ),
    ]
