# Generated by Django 6.0.3 on 2026-04-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_ia', '0001_initial'),
        ('projetos', '0003_alter_projeto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(default='', max_length=255)),
                ('caminho_arquivo', models.CharField(default='', max_length=500)),
                ('arquivo', models.FileField(upload_to='relatorios/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'db_table': 'relatorios_conformidade',
            },
        ),
    ]
