# Generated by Django 5.2.12 on 2026-04-25 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_ia', '0002_relatorioconformidade'),
        ('projetos', '0005_merge_20260420_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioconformidade',
            name='caminho_arquivo',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='relatorioconformidade',
            name='nome_arquivo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='relatorioconformidade',
            name='projeto',
            field=models.ForeignKey(db_column='projeto_id', default='', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='relatorioconformidade',
            table='relatorios_conformidade',
        ),
    ]
