# Generated by Django 6.0.3 on 2026-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_ia', '0003_relatorioconformidade_caminho_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioconformidade',
            name='geracao_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relatorioconformidade',
            name='responsavel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
