# Generated by Django 6.0.3 on 2026-03-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id_norma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ano', models.IntegerField()),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='nbr-pdf/')),
            ],
            options={
                'db_table': 'normas',
                'unique_together': {('codigo', 'ano', 'serie')},
            },
        ),
    ]
