# Generated by Django 6.0.3 on 2026-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='hash_arquivo',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
